### ISSUE TITLE
Create JSON format content for the digest channel

### ISSUE THREAD

**Issue by gnott** [elifesciences/digest-parser#16]
Plan is to format the digest content into a JSON schema compatible format for ingestion and/or publishing.

**Comment by giorgiosironi** [comment]
I am missing a piece here: currently the article JSON ingested in Lax contains digest content:
```
$ curl -v "https://prod--gateway.elifesciences.org/articles/32794" | jq .digest
{
  "doi": "10.7554/eLife.32794.002",
  "content": [
    {
      "text": "Cells with complex interlocking shapes, similar to pieces of a jigsaw puzzle, cover the surface of many leaves. Why do these curiou
s shapes form, and what benefit do they provide to the plant?",
      "type": "paragraph"
    },
    {
      "text": "Plant cells are like small balloons surrounded by a strong cell wall. Their internal pressure can be higher than the pressure in a 
car tire. It is this pressure that gives non-woody plant tissue its shape. Take away the pressure, and the plant wilts.",
      "type": "paragraph"
    },
...
```
since it is shown in the `eLife digest` section at https://elifesciences.org/articles/32794
Is there other content in the XML that needs to be parsed and added there?

**Comment by gnott** [comment]
Regarding the Digest Channel and its features, I'm not entirely clear. We will have some additional data available, which is current (and will continue to be) displayed at Medium (title, summary, image, tags, etc.). I'm not sure if we still want to pull this from Medium itself, or whether it will also be in an eLife data store. @Melissa37 may know more, and it is still open for comment.

**Comment by Melissa37** [comment]
Hi there

I am awaiting the next meeting that Peter sets up in order to discuss all this stuff.
It's good we're identifying the "stuff" we need to cover, but Peter and Features need to lead on what content is needed for each aspect of this and whether it is stored in our system.

Sorry to not be helpful, but I would really like to have a meeting with Features before we go further on.

I've pinged about this already - he's not on GitHub.

Cheers
M

**Comment by gnott** [comment]
So far, the individual attributes of the ``Digest`` and ``Image`` objects in https://github.com/elifesciences/digest-parser/blob/develop/digestparser/objects.py are some possible individual values that could be stored somewhere. 

These will be converted to JATS and to HTML content. They could also potentially be converted to title attributes, paragraph blocks, image block, add a pub date, if in the end to best display the data is to keep the individual data separate.

**Comment by giorgiosironi** [comment]
> Peter and Features need to lead on what content is needed for each aspect of this and whether it is stored in our system.

It's the same on our end2end, awaiting a specification, to then decide on the architecture. I think this can be considered blocked until more is known.

**Comment by Melissa37** [comment]
Agree @giorgiosironi

**Comment by gnott** [comment]
Closing in favour of https://github.com/elifesciences/jira-import/issues/4301.
