### ISSUE TITLE
Images: Upload them to Medium, or host them elsewhere

### ISSUE THREAD

**Issue by gnott** [elifesciences/digest-parser#18]
My understanding from the Medium API docs (https://github.com/Medium/medium-api-docs) is if an ``<img>`` tag is in the post content then Medium will download it from there, if we added the image to a bucket or CDN separately.

Alternatively, we could upload the image as a separate step directly to Medium via their API, it will return a URL for that copy, and we can then include that in the post content.

If the image will appear on journal anyway, we probably want to store it in an eLife CDN, and then we could set the ``<img>`` tag ``src`` to load it from there.

**Steps to completion:**
- [x] Medium post content formatting
- [x] CDN configuration
- [x] Ingest workflow logic, add the image to the bucket

**Comment by gnott** [comment]
The prevailing solution is to upload the image to a bucket, and in the Medium post content it can load it with the ``<img>`` tag.

The folder or path for the images is to be determined.

**Comment by giorgiosironi** [comment]
The usual `cdn.elifesciences.org`?

**Comment by gnott** [comment]
I agree ``cdn.elifesciences.org``.

 Into a subfolder I would assume. An option I suggest is to add them to the ``prod-elife-published`` bucket into a new subfolder ``/digest``, then we can add an additional path to the CDN with that subfolder, as it done with the ``/articles`` path.

**Comment by giorgiosironi** [comment]
Yes, seems easy enough:
https://github.com/elifesciences/builder/blob/master/projects/elife.yaml#L728-L730
Note:
- that configuration isn't used by the `prod` environment, as that part is preexisting and manually configured
- CDN will be ported to Fastly in the near future, be aware it will vanish from CloudFront's console

**Comment by gnott** [comment]
The digest image is added to the bucket by the ``elife-bot`` project in the ``DepositDigestIngestAssets`` activity (https://github.com/elifesciences/elife-bot/blob/develop/activity/activity_DepositDigestIngestAssets.py), current part of the ``IngestDigest`` workflow (https://github.com/elifesciences/elife-bot/blob/develop/workflow/workflow_IngestDigest.py). The workflow is invoked when a ``.zip`` package for a digest is uploaded to the bucket, and the bucket notification will result in a workflow execution.
