### ISSUE TITLE
Docx change from FULL ARTICLE DOI to MANUSCRIPT NUMBER

### ISSUE THREAD

**Issue by gnott** [elifesciences/digest-parser#40]
In discussion today, the full DOI format in the docx file is not required and can instead be abbreviated to just the manuscript number.

So instead of

**FULL ARTICLE DOI**
https://doi.org/10.7554/eLife.99999

in the docx it will be

**MANUSCRIPT NUMBER**
99999

In the ``.cfg`` file for the project it will have a formatting pattern to turn the manuscript number into the DOI.

@giorgiosironi this may affect the end2end tests. I can see if I can PR the change for your review.

**Comment by giorgiosironi** [comment]
This is the place: https://github.com/elifesciences/elife-spectrum/blob/master/spectrum/generator.py#L93-L95

The tricky thing is that the bot should support both `FULL ARTICLE DOI` and `MANUSCRIPT NUMBER` for backward compatibility; then the tests can switch and be integrated; and only then the old case can be removed.

**Comment by gnott** [comment]
I considered support for both, although one will have to be preferred over the other. I'll see if I can do it that way.
