### ISSUE TITLE
Create S3 bucket for files to be deposited into

### ISSUE THREAD

**Issue by gnott** [elifesciences/digest-parser#6]

**Comment by gnott** [comment]
Are there any particular bucket names we would like for where digest content is dropped into? @Melissa37 or @giorgiosironi

**Comment by Melissa37** [comment]
Humm, I don't really have an opinion...

elife-digest-raw maybe?

Stuart might have a preference?

M

**Comment by giorgiosironi** [comment]
With the usual pattern, `$environment-elife-$something`, in this case I'd go as far as 
```
end2end-elife-bot-digests-input
continuumtest-elife-bot-digests-input
prod-elife-bot-digests-input
```
(or something similar to input that makes clear this is the place where to put files, not to read them from)

**Comment by gnott** [comment]
I like the ``input`` term, and ``digests`` makes sense :)  Thanks!  These names won't really matter to users of the system I think, so it's more of an internal name.

This is not the bucket where data will be stored prior to publication, that one is TBD.
