### ISSUE TITLE
Create workflows and activities to process a file dropped into S3

### ISSUE THREAD

**Issue by gnott** [elifesciences/digest-parser#7]

**Comment by gnott** [comment]
At least two workflows will make the process possible I think

1. ``DigestIngest`` worfklow
1. ``DigestPublish`` workflow

Description of ``DigestIngest``: 
* Normally triggered by adding a file to an S3 bucket (a ``.docx`` file or a ``.zip`` file, if it contains a ``docx`` and an image). 
* Parse the ``docx`` file into the HTML-style intermediate format. 
* Convert a portion of the data to ``JATS`` format and send to the typesetters, possibly also CCing by email to eLife recipients
* Store the content and image in an S3 bucket, awaiting publication
* **TBD:** Send the content to a service to make it accessible via the API to the journal, for previewing unpublished digest channel matieral
* Can be run again for the same digest to overwrite old or incorrect data. The ID in the file name will be the key for the specific article

Description of ``DigestPublish``:
* To be triggered when the VoR article a digest is associated with is published. The trigger for it can be added to the existing ``PostPerfectPublication`` workflow
* Download the content and optional image from the S3 bucket which has been waiting for the publication trigger
* **TBD:** Set the unpublished, ingested digest content already stored in the API machinery to be published. If this is not how it will work, then now send the content to the appropriate place for it to appear on the journal
* Use the content from the S3 bucket to format the Medium post content, adding in the optional image, footer, link to the related article. POST to Medium's API as a draft post, and then notify eLife it is created and ready to review, further edit with keywords / tags, etc., and to publish manually on Medium

The separate publishing workflow is partially to satisfy the request that a Medium post for the digest should not be added there - even in draft form - until the article it relates to is published, so the Medium post is not accidentally published before the full article.

@giorgiosironi if you have thoughts about the workflow names, what they will do, or any comments about bucket storage or anything else in that regard.

@Melissa37 if you want to review the logic and whether it fits with the plan, and you can share it with others for comment.

**Comment by gnott** [comment]
The Medium post will also be added to a ``publication`` on Medium. It doesn't seem to be included in https://github.com/Medium/medium-sdk-python which I'm testing with now, but the API docs at  https://github.com/Medium/medium-api-docs lists a separate endpoint where you can create a post in a particular publication. 

Setting the publication manually on Medium, which is already being done now, is an option.

**Comment by gnott** [comment]
Thanks Giorgio!

1. I thought the workflow names would make them more distinctive from the others, but I agree with you for verb-noun format, and shall go for ``IngestDigest`` and ``PublishDigest``.

1. For the storage part, it does not need to be accessible to any human operator, so we can probably reuse the ``elife-bot`` bucket and create a ``digests/`` path :+1: 

1. The DOCX file has a specific, structured format, and this repo is already parsing it and producing the outputs. The authoring is in the DOCX, then the converted content will be to the typesetters. The Medium post, from the DOCX content, will be created in draft form to be reviewed before publication as well. Those steps will be the stages of review, if something went wrong in the DOCX conversation that is where it can be detected (beyond technical parsing errors).

1. The typesetters include the digest content in the XML file as well as the PDF, and is why they receive it and prior to publication :+1: 

1. I think Lax as storage for the journal part is a good option too. To be worked out is the particular data attributes, such as title, related article, paragraphs, keywords, featured image, etc.

**Comment by Melissa37** [comment]
Thanks G and G, have read this and makes sense to me, and shared it with Peter and Staurt (no feedback yet).
Good plan!

**Comment by gnott** [comment]
Two separate issues created https://github.com/elifesciences/jira-import/issues/4302 and https://github.com/elifesciences/jira-import/issues/4303 to continue this issue, so I will close this earlier issue.
